# Generated by Django 3.2.9 on 2021-11-06 21:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(max_length=2500, validators=[django.core.validators.MinLengthValidator(30)])),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Contact Messages',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['date_created'],
            },
        ),
    ]
